[tool.poetry]
name = "play-aws-python"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8.0"
boto3 = "1.20.1"

[tool.poetry.dev-dependencies]
black = {version = "^21.10b0", allow-prereleases = true}
